### ISSUE TITLE
Forma de disponibilização do app

### ISSUE THREAD

**Issue by LorhanSohaky** [vinql/UFSCarPlanner#3]
Atualmente o aplicativo está em forma de `apk` dentro do próprio repositório. A minha sugestão é de remover do repo e colocar na parte de [release](https://github.com/vinql/UFSCarPlanner/releases).

**Comment by vinql** [comment]
Obrigado pela sugestão! Pessoalmente, eu não sabia que havia uma aba para isso, e na próxima vez que atualizarmos o master o pacote de instalação vai ser disponibilizado no local adequado.
